name: Build Rising

on:
  workflow_dispatch:
jobs:
  building:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
       - name: Git config
         run: git config --global user.name "Mark Fomin"; git config --global user.email "androidbuild@difhel.dev"

       - name: Download repository files
         uses: actions/checkout@v2
         
       - name: Installation of build essentials
         run: sudo apt install repo
       
       - name: Repo init exist checking
         run: if [ -d ".repo" ]; then echo "repo has been initialized"; export init=1; else echo "Need to init new one"; export init=0; fi;
       
       - name: Repo init (if needed)
         run: if [[ $init == 0 ]]; then echo "Initing new repo .repo"; repo init --depth=1 --no-repo-verify -u https://github.com/RisingTechOSS/android -b thirteen -g default,-mips,-darwin,-notdefault; fi;
       
       - name: Repo sync
         run: repo sync -c --no-clone-bundle --optimized-fetch --prune --force-sync -j$(nproc --all)
         
       - name: Commit repo (we do not need to sync it every time, right?)
         uses: stefanzweifel/git-auto-commit-action@v4
       
       - name: Inherit Lineage vendor common stuffs
         run: $(call inherit-product, vendor/lineage/config/common_full_phone.mk)
         
       - name: Build environment setup
         run: . build/envsetup.sh
       
       - name: Brunch Oriole (userdebug variant)
         run: brunch "device_oriole" userdebug
         
       - name: Lunch
         run: lunch lineage_oriole-userdebug
        
       - name: Build
         run: mka bacon -jX
         
       
